substitutions:
  name: "6-ch-monitor"
  friendly_name: "6-ch-monitor"
  ch1: "ch_1"   #可根据需要修改名称
  ch2: "ch_2"   #可根据需要修改名称
  ch3: "ch_3"    #可根据需要修改名称
  ch4: "ch_4"    #可根据需要修改名称
  ch5: "ch_5"  #可根据需要修改名称
  ch6: "ch_6"     #可根据需要修改名称
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: carrot8848.6-ch-monitor
    version: "1.0"
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "6-Ch-Electricity-Monitor"
    password: ""

captive_portal:
web_server:
  port: 80
external_components:
  - source:
      type: git
      url: https://github.com/carrot8848/ESPHome/
      ref: main
  - source: github://dentra/esphome-components
status_led:
  pin: GPIO10
uart:
  - id: uart_bus
    rx_pin: 4
    tx_pin: 5
    baud_rate: 9600
#如需使用PZEM-004T，取消下方注释，PZEM-004T和PZEM-DC无法同时使用
  - id: uart_bus2
    rx_pin: 6
    tx_pin: 7
    baud_rate: 9600
#如需使用PZEM-DC，取消下方注释，PZEM-004T和PZEM-DC无法同时使用
  # - id: uart_bus3
  #   rx_pin: 0
  #   tx_pin: 1
  #   baud_rate: 9600
  
#如需使用PZEM-004T，取消下方注释，PZEM-004T和PZEM-DC无法同时使用
modbus:
  - uart_id: uart_bus2
    id: mod_bus1
#如需使用PZEM-DC，取消下方注释，PZEM-004T和PZEM-DC无法同时使用
#   - uart_id: uart_bus3
#     id: mod_bus2

sensor:
  - platform: bl0906
    uart_id: uart_bus
    update_interval: 10s   
    Frequency:
      name: 'Frequency'
    Temperature:
      name: 'Temperature'
    Voltage:
      name: 'Voltage'
    Current_1:
      name: "${ch1} current"    
    Current_2:
      name: "${ch2} current"    
    Current_3:
      name: "${ch3} current"    
    Current_4:
      name: "${ch4} current"    
    Current_5:
      name: "${ch5} current"    
    Current_6:
      name: "${ch6} current"  
    Power_1:
      name: "${ch1} power"
    Power_2:
      name: "${ch2} power"
    Power_3:
      name: "${ch3} power"
    Power_4:
      name: "${ch4} power"
    Power_5:
      name: "${ch5} power"      
    Power_6:
      name: "${ch6} power"
    Power_sum:
      name: "6-ch sum power"
    Energy_1: 
      id: ch1_energy
      name: "${ch1} energy"
    Energy_2: 
      id: ch2_energy
      name: "${ch2} energy"
    Energy_3: 
      id: ch3_energy
      name: "${ch3} energy"
    Energy_4: 
      id: ch4_energy
      name: "${ch4} energy"
    Energy_5: 
      id: ch5_energy
      name: "${ch5} energy"
    Energy_6: 
      id: ch6_energy
      name: "${ch6} energy" 
    Energy_sum: 
      id: chs_energy_sum
      name: "6-ch energy" 

  - platform: "energy_statistics"
    total: ch1_energy
    energy_today:
      name: "${ch1} energy_today"
    energy_yesterday:
      name: "${ch1} energy_yesterday"
    energy_week:
      name: "${ch1} energy_week"
    energy_month:
      name: "${ch1} energy_month"
  - platform: "energy_statistics"
    total: ch2_energy
    energy_today:
      name: "${ch2} energy_today"
    energy_yesterday:
      name: "${ch2} energy_yesterday"
    energy_week:
      name: "${ch2} energy_week"
    energy_month:
      name: "${ch2} energy_month"
  - platform: "energy_statistics"
    total: ch3_energy
    energy_today:
      name: "${ch3} energy_today"
    energy_yesterday:
      name: "${ch3} energy_yesterday"
    energy_week:
      name: "${ch3} energy_week"
    energy_month:
      name: "${ch3} energy_month"
  - platform: "energy_statistics"
    total: ch4_energy
    energy_today:
      name: "${ch4} energy_today"
    energy_yesterday:
      name: "${ch4} energy_yesterday"
    energy_week:
      name: "${ch4} energy_week"
    energy_month:
      name: "${ch4} energy_month"
  - platform: "energy_statistics"
    total: ch5_energy
    energy_today:
      name: "${ch5} energy_today"
    energy_yesterday:
      name: "${ch5} energy_yesterday"
    energy_week:
      name: "${ch5} energy_week"
    energy_month:
      name: "${ch5} energy_month"
  - platform: "energy_statistics"
    total: ch6_energy
    energy_today:
      name: "${ch6} energy_today"
    energy_yesterday:
      name: "${ch6} energy_yesterday"
    energy_week:
      name: "${ch6} energy_week"
    energy_month:
      name: "${ch6} energy_month"

#如需使用PZEM-004T，取消下方注释，PZEM-004T和PZEM-DC无法同时使用
  - platform: pzemac
    current:
      name: "PZEM Current"
    voltage:
      name: "PZEM Voltage"
    energy:
      name: "PZEM Energy"
      id: energy
      filters:
        # Multiplication factor from Wh to kWh is 0.001
        - multiply: 0.001
      unit_of_measurement: kWh
    power:
      name: "PZEM Power"
      id: pzemac_power
      filters:
        # Multiplication factor from W to kW is 0.001
       - multiply: 0.001
      unit_of_measurement: kW
    frequency:
      name: "PZEM Frequency"
    power_factor:
      name: "PZEM Power Factor"
    update_interval: 10s
    modbus_id: mod_bus1
  - platform: "energy_statistics"
    total: energy
    energy_today:
      name: "PZEM Energy Today"
    energy_yesterday:
      name: "PZEM Energy Yesterday"
    energy_week:
      name: "PZEM Energy Week"
    energy_month:
      name: "PZEM Energy Month"
  
#如需使用PZEM-DC，取消下方注释，PZEM-004T和PZEM-DC无法同时使用
  # - platform: pzemdc
  #   modbus_id: mod_bus2
  #   current:
  #     name: "PZEM-003 Current"
  #   voltage:
  #     name: "PZEM-003 Voltage"
  #   power:
  #     name: "PZEM-003 Power"
  #   energy:
  #     name: "PZEM-003 Energy"
  #   update_interval: 10s

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "Energy_meter WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Energy_meter WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

time:
  - platform: sntp
    id: my_time
    servers: 120.25.108.11
text_sensor:
  - platform: wifi_info
    ip_address:
      name: Energy_meter IP Address
    ssid:
      name: Energy_meter Connected SSID
    bssid:
      name: Energy_meter Connected BSSID
    mac_address:
      name: Energy_meter Mac Wifi Address
    # scan_results:
    #   name: Energy_meter Latest Scan Results
    dns_address:
      name: Energy_meter DNS Address 
